apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "context.fullname" . }}
  labels:
{{ include "context.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "context.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "context.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    ## imagePullSecrets
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      ## containers
      containers:
        - name: test-web-client
          image: {{ template "context.image" . }}
          imagePullPolicy: {{ .Values.context.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.context.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      ## node selector
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      ## affinity
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      ## tolerations
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
