variables:
  DOCKER_DRIVER: overlay2
  EFF_NO_LINK_RULES: 'true'
  GIT_CLEAN_FLAGS: -ffdx -e /dist/
  NODE_OPTIONS: --max-old-space-size=2048
  PARSER_NO_WATCH: 'true'

build image:
  only:
    - dev
    - master
  stage: build
  image: docker:git
  services:
    - name: docker:dind
  before_script:
    - docker info
    - docker login ${DOCKER_REGISTRY_SERVER} -u ${DOCKER_REGISTRY_USER} -p ${DOCKER_REGISTRY_PASSWORD}
  script:
    # - if [ "master" == "$CI_COMMIT_REF_NAME" ]; then export IMAGE_SUFFIX="-prod"; fi
    - export IMAGE=${DOCKER_REGISTRY_SERVER}/m-fe-rtw
    # - docker build --tag $IMAGE:$CI_COMMIT_SHA --tag $IMAGE:latest -f scripts/docker/Dockerfile .
    # - docker push $IMAGE:$CI_COMMIT_SHA
    # - docker push $IMAGE:latest
    - sh ./scripts/docker/build-on-gitlab.sh
